### ISSUE TITLE
Scriptorium new command fails when making a new paper

### ISSUE THREAD

**Issue by DTChuck** [jasedit/scriptorium#11]
Scriptorium fails when creating a new paper. I tried with both the ieeetran template and the report template. Traceback is below.

Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 9, in <module>
    load_entry_point('scriptorium==2.0.0', 'console_scripts', 'scriptorium')()
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 78, in main
    args.func(args)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 43, in create
    if not scriptorium.create(args.output, args.template, force=args.force, config=args.config):
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/papers.py", line 117, in create
    shutil.copyfile(giname, os.path.join(paper_dir))
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 21] Is a directory: 'test'

**Comment by jasedit** [comment]
Update and try again, I think this is fixed

**Comment by DTChuck** [comment]
Paper was created with a folder containing a .mmd file.
