### ISSUE TITLE
Error with scriptorium make output file name

### ISSUE THREAD

**Issue by DTChuck** [jasedit/scriptorium#13]
Called scriptorium make from directory with paper.mmd (folder name test). 

Ryans-MacBook-Pro-2:test ryan$ scriptorium make -o test
Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 9, in <module>
    load_entry_point('scriptorium==2.0.0', 'console_scripts', 'scriptorium')()
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 78, in main
    args.func(args)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 12, in make
    pdf = scriptorium.to_pdf(args.paper, use_shell_escape=args.shell_escape)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/papers.py", line 76, in to_pdf
    print('LaTeX conversion failed with the following output:\n', output)
UnboundLocalError: local variable 'output' referenced before assignment

**Comment by jasedit** [comment]
Duplicates #12, fix is in progress there
