### ISSUE TITLE
Template command with list option fails with Unicode error

### ISSUE THREAD

**Issue by DTChuck** [jasedit/scriptorium#14]
Attempted to check the template list that is installed. I verified that the TEMPLATE_DIR is correct in the scriptorium config file.

Ryans-MacBook-Pro-2:scriptorium ryan$ scriptorium template -l
Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 9, in <module>
    load_entry_point('scriptorium==2.0.0', 'console_scripts', 'scriptorium')()
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 102, in main
    args.func(args)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 44, in template_cmd
    templates = scriptorium.all_templates(args.template_dir)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/templates.py", line 15, in all_templates
    for dirpath, _, filenames in os.walk(dname):
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by jasedit** [comment]
Update and try again, should be fixed in 930e4f773307fb61abf3f26fc51db6a92a801df6

**Comment by DTChuck** [comment]
Fixed. No errors
