### ISSUE TITLE
Template update fails with invalid expression

### ISSUE THREAD

**Issue by DTChuck** [jasedit/scriptorium#15]
Called template update on both ieeetran and report. Same result.

Ryans-MacBook-Pro-2:scriptorium ryan$ scriptorium template -u report
Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 9, in <module>
    load_entry_point('scriptorium==2.0.0', 'console_scripts', 'scriptorium')()
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 102, in main
    args.func(args)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 41, in template_cmd
    scriptorium.update_template(args.update)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/templates.py", line 78, in update_template
    treeish_re = re.compile(r'[A-Za-z0-9_-.]+')
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range

**Comment by jasedit** [comment]
Test out a27ca70dd2b19c5b8680ae6ec6c860a8b23fcb5a

**Comment by DTChuck** [comment]
Correctly updated both report and ieeetran. No errors.
