### ISSUE TITLE
Subtle difference in how Python 2 mmap stuff works causing error when building papers.

### ISSUE THREAD

**Issue by newtonj** [jasedit/scriptorium#52]
When running ```scriptorium build``` under Python 2, the following TypeError exception is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/__main__.py", line 161, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/__main__.py", line 16, in build_cmd
    pdf = scriptorium.to_pdf(args.paper, use_shell_escape=args.shell_escape, flatten=args.flatten)
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/papers.py", line 61, in to_pdf
    fname = paper_root(paper_dir)
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/papers.py", line 28, in paper_root
    if get_template(fname):
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/papers.py", line 48, in get_template
    idx = mm.find(bytearray(blank_line, 'utf-8'))
TypeError: find() argument 1 must be string or read-only buffer, not bytearray
```

This does not occur when running under Python 3.

**Comment by jasedit** [comment]
I think I have a bug fix available in 87aaa5b, but I can't test Python 2 on this machine. Any chance you could give that branch a shot?

Also, Travis doesn't like it when you force push a commit out from under it. Whoops.
