### ISSUE TITLE
Missing package latex

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/scriptorium#80]
When running the `scriptorium doctor` command, it returns `Missing package latex` on a new install of Ubuntu 16.04.

**Comment by jasedit** [comment]
Is `biber` installed? The LaTeX package tests for the existence of latex and biber, and by default, biber isn't included in LaTeX.

**Comment by rjgriffin42** [comment]
That fixes that error, but now raises the error 
```
Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/__main__.py", line 181, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/__main__.py", line 17, in build_cmd
    keep_comments=args.keep_comments)
  File "/usr/local/lib/python2.7/dist-packages/scriptorium/papers.py", line 147, in to_pdf
    subprocess.check_output(pdf_cmd, env=new_env)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
when trying to build something.

**Comment by jasedit** [comment]
What's the output of `scriptorium config -l`? I'm going to guess that this is a mismatch between what the doctor command checks (`pdflatex`), and what you're configured to use `xelatex`

**Comment by rjgriffin42** [comment]
that is correct. 

```
LATEX_CMD: xelatex
TEMPLATE_DIR: /home/robert/.scriptorium/templates/
```

but I now do not remember what the fix was for that.

**Comment by jasedit** [comment]
If you want to switch to `pdflatex`, you can switch with `scriptorium config LATEX_CMD pdflatex`. If you want to stick with `xelatex`, just install the `xelatex` package and it should fix.

The `find_missing_packages()` function should also respect this configuration value for consistency.

**Comment by rjgriffin42** [comment]
That did the trick, thanks again!
