### ISSUE TITLE
Invoking scriptorium make fails.

### ISSUE THREAD

**Issue by newtonj** [jasedit/scriptorium#9]
When trying out the new Python system, running the following on a properly configured paper directory bombs out:

`scriptorium make papers/thesis/main`

The error produced indicates a failure to import a module.

```
Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 11, in <module>
    load_entry_point('scriptorium==2.0.0', 'console_scripts', 'scriptorium')()
  File "/home/hakujin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565,
 in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/hakujin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2598,
 in load_entry_point
    return ep.load()
  File "/home/hakujin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2258,
 in load
    return self.resolve()
  File "/home/hakujin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2264,
 in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named main
```

As far as I know, all python dependencies are satisfied at this point.

**Comment by newtonj** [comment]
For reference, the command was invoked at the root of the scriptorium directory, in case that messes with the path logic.

**Comment by jasedit** [comment]
Try the latest version of the branch, I think this is fixed now

**Comment by newtonj** [comment]
After running setup.py again, everything worked like a charm. Good stuff.
