### ISSUE TITLE
_MMD_LIB set to null ?

### ISSUE THREAD

**Issue by f22raptorroland** [jasedit/scriptorium#94]
I get this error whatever I try to build:

C:\Users\Roland\Desktop\Thesis\Compile>scriptorium build mypaper.mmd
Traceback (most recent call last):
  File "c:\users\roland\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\roland\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Roland\AppData\Local\Programs\Python\Python39\Scripts\scriptorium.exe\__main__.py", line 7, in <module>
  File "c:\users\roland\appdata\local\programs\python\python39\lib\site-packages\scriptorium\__main__.py", line 181, in main
    args.func(args)
  File "c:\users\roland\appdata\local\programs\python\python39\lib\site-packages\scriptorium\__main__.py", line 16, in build_cmd
    pdf = scriptorium.to_pdf(args.paper, use_shell_escape=args.shell_escape, flatten=args.flatten,
  File "c:\users\roland\appdata\local\programs\python\python39\lib\site-packages\scriptorium\papers.py", line 137, in to_pdf
    tex_fp.write(pymmd.convert(mmd_fp.read(), fmt=pymmd.LATEX, dname=mmd, ext=pymmd.SMART))
  File "c:\users\roland\appdata\local\programs\python\python39\lib\site-packages\pymmd-0.4.0-py3.9.egg\pymmd\mmd.py", line 123, in convert
    source, _ = _expand_source(source, dname, fmt)
  File "c:\users\roland\appdata\local\programs\python\python39\lib\site-packages\pymmd-0.4.0-py3.9.egg\pymmd\mmd.py", line 83, in _expand_source
    _MMD_LIB.g_string_new.restype = ctypes.POINTER(GString)
AttributeError: 'NoneType' object has no attribute 'g_string_new'

**Comment by f22raptorroland** [comment]
I don't have the Paper Metadata set up but I don't think that should be an issue. 

It would be such an awesome tool if it worked.

**Comment by f22raptorroland** [comment]
Ok found it. 

It could not load the libmultimarkdown.dll (because it does not come with Multimarkdown 6), so I fiddled around with the path env. var. , still nothing.

Ended up copying the libmultimarkdown.dll to system32, and changed the lib loading code (only the last line)

It's brute force but I have 2 days to finish my thesis

`def load_mmd():
    """Loads libMultiMarkdown for usage"""
    global _MMD_LIB
    global _LIB_LOCATION
    try:
        lib_file = 'libMultiMarkdown' + SHLIB_EXT[platform.system()]
        _LIB_LOCATION = os.path.abspath(os.path.join(DEFAULT_LIBRARY_DIR, lib_file))

        if not os.path.isfile(_LIB_LOCATION):
            _LIB_LOCATION = ctypes.util.find_library('MultiMarkdown')

        _MMD_LIB = ctypes.cdll.LoadLibrary(_LIB_LOCATION)
    except:
        _MMD_LIB = ctypes.cdll.LoadLibrary('libMultiMarkdown')`
